include:
  - admin/compose.dev.yaml

services:
  gateway:
    image: caddy:2.8-alpine
    ports: [ 80:80, 443:443 ]
    cap_add: [ NET_ADMIN ]
    restart: unless-stopped
    env_file: [ .env ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    entrypoint: caddy run --watch --config /etc/caddy/Caddyfile

  web:
    build:
      context: web
      target: dev
    extends:
      file: compose.yaml
      service: web
    volumes:
      - ./web/node_modules:/app/node_modules:rw
      - ./web/.svelte-kit:/app/.svelte-kit:rw
      - ./web/src:/app/src:ro
      - ./web/static:/app/static:ro

  db:
    extends:
      file: compose.yaml
      service: db

volumes:
  db:


secrets:
  postgres_db:
    file: "./secrets/postgres/db"
  postgres_user:
    file: "./secrets/postgres/user"
  postgres_password:
    file: "./secrets/postgres/password"
