include:
  - admin/compose.yaml

services:
  gateway:
    image: caddy:2.8-alpine
    ports: [ 80:80, 443:443 ]
    cap_add: [ NET_ADMIN ]
    restart: unless-stopped
    env_file: [ .env ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  web:
    image: ghcr.io/clayenapps/workspaces-web:latest
    build: web
    init: true
    expose: [ 3000 ]
    restart: unless-stopped
    env_file: [ .env ]

  api:
    image: ghcr.io/clayenapps/workspaces-api:latest
    build: api
    init: true
    expose: [ 3000 ]
    restart: unless-stopped
    env_file: [ .env ]

  db:
    image: postgres
    expose: [ 5432 ]
    shm_size: 128mb
    restart: unless-stopped
    env_file: [ .env ]
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB_FILE: /run/secrets/pg_db
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets: [ pg_db, pg_user, pg_password ]

volumes:
  caddy_data:
  caddy_config:
  db:


secrets:
  pg_db:
    file: "./secrets/postgres/db"
  pg_user:
    file: "./secrets/postgres/user"
  pg_password:
    file: "./secrets/postgres/password"
