server:
  address: tcp://:9091/auth
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"

totp:
  disable: false
  issuer: "ClayenApps Workspaces"

webauthn:
  disable: false

authentication_backend:
  file:
    watch: true
    path: "/config/users.yml"

identity_validation:
  reset_password:
    jwt_secret:  {{ secret "/run/secrets/authelia_reset_password_jwt_secret" }}
  elevated_session:
    code_lifespan: '5 minutes'
    elevation_lifespan: '10 minutes'
    characters: 8
    require_second_factor: false
    skip_second_factor: false

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: "one_factor"
  rules:
    - domain: '{{ mustEnv "ADMIN_DOMAIN" }}'
      policy: two_factor
      resources:
      - '^/embed/db([/?].*)?$'

session:
  secret: {{ secret "/run/secrets/authelia_session_secret" }}
  cookies:
    - name: "clayen_workspaces_admin_session"
      domain: '{{ mustEnv "ADMIN_DOMAIN" }}'
      authelia_url: "https://{{ mustEnv "ADMIN_DOMAIN" }}/auth/"
      default_redirection_url: "https://{{ mustEnv "ADMIN_DOMAIN" }}/"
      same_site: "lax"
      inactivity: "5 minutes"
      expiration: "1 hour"
      remember_me: "1 month"

regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  encryption_key: {{ secret "/run/secrets/authelia_storage_encryption_key" }}
  local:
    path: "/config/db.sqlite3"

notifier:
  disable_startup_check: true
  smtp:
    address: "smtp://smtp.resend.com:25"
    timeout: "5 seconds"
    username: "resend"
    password:  {{ secret "/run/secrets/resend_token" }}
    sender: "ClayenApps Workspaces <noreply@clayenkitten.ru>"
    subject: "ClayenApps Workspaces: {title}"
